package it.valeriovaudi.emarket.event.model;

public enum EventType {
    IDENTITY_VALIDATION_ERROR,
    CHANGE_PASSWORD,
    VALIDATION_ERROR,
    ACCOUNT_NOT_FOUNT,
    SAVE_NEW_ACCOUNT_DATA,
    CREATION_ACCOUNT_CONFLICT,
    SAVE_ACCOUNT_DATA,
    DELETE_AN_ACCOUNT;
}
