server:
  port: 8888

management:
  security:
    enabled: false

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          searchLocations: file://${LOCAL_REPO}
        git:
          uri: file://${GIT_LOCAL_REPO}