version: "2.1"

services:
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15671:15671"
#      - "15672:15672"
#
#  cassandra:
#    image: cassandra
#    volumes:
#      - "${CASSANDRA_LOCAL_VOLUME}:/var/lib/cassandra"
#    ports:
#      - "9042:9042"
#
#  database:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "${MONGO_LOCAL_VOLUME}:/data/db"
