version: "2.1"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - memcache

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - messaging

  cassandra:
    image: cassandra
    volumes:
      - "${CASSANDRA_LOCAL_VOLUME}:/var/lib/cassandra"
    ports:
      - "9042:9042"
    networks:
      - cassandra

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - "${MONGO_LOCAL_VOLUME}:/data/db"
    networks:
      - mongo

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - database

networks:
  memcache:
    driver: bridge
  database:
    driver: bridge
  messaging:
    driver: bridge
  cassandra:
    driver: bridge
  mongo:
    driver: bridge