spring:
  data:
    cassandra:
      keyspace-name: purchaseOrderEventKeyspace
  cloud:
    stream:
      bindings:
        purchaseOrderEventOutboundChannel:
          content-type: application/json

server:
  use-forward-headers: true

external-service:
  base-uri-schema:
    goods-in-product-catalog: http://api-gateway/api/v1/product-catalog-service/price-list/{priceListId}/goods/{goodsId}
    account: http://api-gateway/api/v1/account-service/account/{userName}

security:
  oauth2:
    resource:
     id: oauth2-resource
     user-info-uri: http://localhost:9090/account/userInfo.json

eureka:
  client:
    healthcheck:
      enabled: true