version: "2.1"

services:
  account-service:
    image: e-market/account-service-server:lastest
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - cloudnativeinfrastructure_security
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging
      - baseinfrastructure_cassandra
      - baseinfrastructure_memcache
      - baseinfrastructure_database


  product-catalog-service:
    image: e-market/product-catalog-service-server:lastest
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - cloudnativeinfrastructure_security
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging
      - baseinfrastructure_cassandra
      - baseinfrastructure_memcache
      - baseinfrastructure_mongo

  purchase-order-service:
    image: e-market/purchase-order-service-server:lastest
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - cloudnativeinfrastructure_security
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging
      - baseinfrastructure_cassandra
      - baseinfrastructure_memcache
      - baseinfrastructure_mongo


networks:
  cloudnativeinfrastructure_security:
    external: true
  basecloudnativeinfrastructure_discovery:
    external: true
  baseinfrastructure_messaging:
    external: true
  baseinfrastructure_mongo:
    external: true
  baseinfrastructure_cassandra:
    external: true
  baseinfrastructure_database:
    external: true
  baseinfrastructure_memcache:
    external: true